# Generated by Django 4.0.3 on 2024-08-23 03:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100)),
                ('meta_title', models.CharField(blank=True, max_length=150)),
                ('meta_description', models.TextField(blank=True, max_length=300)),
                ('meta_keywords', models.TextField(blank=True, max_length=300)),
                ('bg_banner', models.ImageField(blank=True, upload_to='photos/banner')),
                ('get_in_touch_title', models.CharField(default='Get in touch with us', max_length=300)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('phone_no1', models.CharField(blank=True, max_length=100)),
                ('phone_no2', models.CharField(blank=True, max_length=100)),
                ('email1', models.CharField(blank=True, max_length=100)),
                ('email2', models.CharField(blank=True, max_length=100)),
                ('address1', models.TextField(blank=True, max_length=500)),
                ('address2', models.TextField(blank=True, max_length=500)),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=18)),
                ('message', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
            ],
            options={
                'verbose_name': 'feedback',
                'verbose_name_plural': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='ListingEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_name', models.CharField(blank=True, max_length=500)),
                ('listing_url', models.SlugField(blank=True, max_length=700)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_no', models.CharField(blank=True, max_length=16)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('requirement', models.TextField(blank=True)),
                ('user_id', models.IntegerField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
                ('realtor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realtors.realtor')),
            ],
            options={
                'verbose_name_plural': 'Listing Enquiry',
            },
        ),
    ]
