# Generated by Django 4.0.3 on 2024-08-23 03:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=600, null=True, unique=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='city/%Y/%m/%d/')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.state')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': '1. Cities',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=350, null=True, unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='configuration/%Y/%m/%d/')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': '4. Configurations',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('slug', models.SlugField(blank=True, max_length=600, null=True, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title_tag', models.CharField(default='Real Estate', max_length=255)),
                ('meta_description', models.TextField(blank=True, max_length=255)),
                ('meta_keywords', models.TextField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=600, null=True)),
                ('address', models.TextField(max_length=400, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=20, null=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('mrp_price', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('parking', models.IntegerField(blank=True, null=True)),
                ('sqft', models.IntegerField()),
                ('lot_size', models.CharField(blank=True, max_length=200, null=True)),
                ('floors', models.CharField(blank=True, max_length=300, null=True)),
                ('listing_type', models.CharField(blank=True, choices=[('Buy', 'Buy'), ('Rent', 'Rent')], max_length=150, null=True)),
                ('sale_type', models.CharField(blank=True, choices=[('New Projects', 'New Projects'), ('Resale Properties', 'Resale Properties')], max_length=150, null=True)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('youtube_video_code', models.CharField(blank=True, max_length=400, null=True)),
                ('floor_plan_pdf', models.FileField(blank=True, null=True, upload_to='floorplan/pdf/%Y/%m/%d/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
            ],
            options={
                'verbose_name': 'Listing',
                'verbose_name_plural': '6. Listings',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='ListingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=300, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=350, null=True, unique=True)),
                ('meta_description', models.CharField(blank=True, max_length=255)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='listingcategory/%Y/%m/%d/')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
            ],
            options={
                'verbose_name': 'Listing Category',
                'verbose_name_plural': '3. Listing categories',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Possession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=350, null=True, unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='possession/%Y/%m/%d/')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
            ],
            options={
                'verbose_name': 'Possession',
                'verbose_name_plural': '5. Possessions',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_name', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=600, null=True, unique=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='locality/%Y/%m/%d/')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.city')),
            ],
            options={
                'verbose_name': 'Locality',
                'verbose_name_plural': '2. Localities',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='ListingGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='listing/gallery')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('listing', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': '7. Gallery',
                'ordering': ['-created_on'],
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.listingcategory'),
        ),
        migrations.AddField(
            model_name='listing',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.city'),
        ),
        migrations.AddField(
            model_name='listing',
            name='configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.configuration'),
        ),
        migrations.AddField(
            model_name='listing',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.country'),
        ),
        migrations.AddField(
            model_name='listing',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.developer'),
        ),
        migrations.AddField(
            model_name='listing',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.locality'),
        ),
        migrations.AddField(
            model_name='listing',
            name='possession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.possession'),
        ),
        migrations.AddField(
            model_name='listing',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
        migrations.AddField(
            model_name='listing',
            name='realtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realtors.realtor'),
        ),
        migrations.AddField(
            model_name='listing',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.state'),
        ),
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='floorplan/photo/%Y/%m/%d/')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('listing', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
            ],
            options={
                'verbose_name': 'Floor Plan',
                'verbose_name_plural': '8. Floor Plans',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='amenities/photo/%Y/%m/%d/')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('listing', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
            ],
            options={
                'verbose_name': 'Amenities',
                'verbose_name_plural': '9. Amenities',
                'ordering': ['-created_on'],
            },
        ),
    ]
