# Generated by Django 4.0.3 on 2024-08-23 03:44

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=600, null=True, unique=True)),
                ('country_pic', models.ImageField(blank=True, null=True, upload_to='country/%Y/%m/%d/')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': '1. Countries',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_name', models.CharField(max_length=350)),
                ('slug', models.SlugField(blank=True, max_length=450, null=True, unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, max_length=650)),
                ('photo', models.ImageField(blank=True, upload_to='developer/%Y/%m/%d/')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
            ],
            options={
                'verbose_name': 'Developer',
                'verbose_name_plural': '3. Developers',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=600, null=True, unique=True)),
                ('state_pic', models.ImageField(blank=True, null=True, upload_to='state/%Y/%m/%d/')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.country')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': '2. States',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=350)),
                ('slug', models.SlugField(blank=True, max_length=450, null=True, unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, max_length=650)),
                ('photo', models.ImageField(blank=True, upload_to='project/%Y/%m/%d/')),
                ('project_rera', models.CharField(blank=True, max_length=360, null=True)),
                ('rera_link', models.URLField(blank=True, max_length=600, null=True)),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to='project/qrcode/%Y/%m/%d/')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.developer')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': '4. Projects',
                'ordering': ['-created_on'],
            },
        ),
    ]
