from django.urls import path
from . import views

urlpatterns = [
    path('', views.myadmin, name='myadmin'),
    path('dashboard/', views.myadmin, name='admindashboard'),
    path('edit-profile/', views.edit_adminprofile, name='edit_adminprofile'),
    path('vprofile/', views.mvprofile, name='mvprofile'),
    path('change-password/', views.change_adminpassword, name='change_adminpassword'),
    path('enquiry-detail/<int:pk>/', views.enquiry_detail, name='enquiry_detail'),
    path('delete-enquiry/<int:pk>/', views.delete_enquiry, name='delete_enquiry'),
    path('my-property/', views.myproperty, name='myproperty'),
    path('delete-listing/<int:pk>/', views.delete_listing, name='deletelist'),
    # path('update-user-<int:pk>/', views.admin_update_user,name='admin_update_user'),
    # # path('myadmin/delete-staff/<int:pk>', views.admin_delete_staff,name='admin_delete_staff'),
    # # path('<slug:service_slug>/', views.service_detail, name='service_detail'),
    # # path('inquiry', views.inquiry, name='inquiry'),
    # # path('sector/<slug:sector_slug>/', views.jobpost, name='jobs_by_sector'),
    # path('country/', views.add_country, name='add_country'),
    # path('edit_country/<int:pk>/', views.edit_country, name='edit_country'),
    # path('delete-country/<int:pk>/', views.delete_country, name='delete_country'),
    # path('state/', views.add_state, name='add_state'),
    # path('edit-state/<int:pk>/', views.edit_state, name='edit_state'),
    # path('delete-state/<int:pk>/', views.delete_state, name='delete_state'),
    # path('city/', views.add_city, name='add_city'),
    # path('edit-city/<int:pk>/', views.edit_city, name='edit_city'),
    # path('delete-city/<int:pk>/', views.delete_city, name='delete_city'),
    # path('sector/', views.add_sector, name='add_sector'),
    # path('edit-sector/<int:pk>/', views.edit_sector, name='edit_sector'),
    # path('delete-sector/<int:pk>/', views.delete_sector, name='delete_sector'),
    # path('add-company/', views.add_company, name='add_company'),
    # path('edit-company/<int:pk>/', views.edit_company, name='edit_company'),
    # path('delete-company/<int:pk>/', views.delete_company, name='delete_company'),
    # path('jobtype/', views.add_jobtype, name='add_jobtype'),
    # path('edit-jobtype/<int:pk>/', views.edit_jobtype, name='edit_jobtype'),
    # path('delete-jobtype/<int:pk>/', views.delete_jobtype, name='delete_jobtype'),
    # path('workmode/', views.add_workmode, name='add_workmode'),
    # path('edit-workmode/<int:pk>/', views.edit_workmode, name='edit_workmode'),
    # path('delete-workmode/<int:pk>/', views.delete_workmode, name='delete_workmode'),
    # path('jobcategory/', views.add_jobcategory, name='add_jobcategory'),
    # path('edit-jobcategory/<int:pk>/', views.edit_jobcategory, name='edit_jobcategory'),
    # path('delete-jobcategory/<int:pk>/', views.delete_jobcategory, name='delete_jobcategory'),
    # path('jobrole/', views.add_jobrole, name='add_jobrole'),
    # path('edit-jobrole/<int:pk>/', views.edit_jobrole, name='edit_jobrole'),
    # path('delete-jobrole/<int:pk>/', views.delete_jobrole, name='delete_jobrole'),
    # path('jobskill/', views.add_skill, name='add_skill'),
    # path('edit-skill/<int:pk>/', views.edit_skill, name='edit_skill'),
    # path('delete-skill/<int:pk>/', views.delete_skill, name='delete_skill'),
    # path('education/', views.add_education, name='add_education'),
    # path('edit-education/<int:pk>/', views.edit_education, name='edit_education'),
    # path('delete-education/<int:pk>/', views.delete_education, name='delete_education'),
    # path('experience/', views.add_experience, name='add_experience'),
    # path('edit-experience/<int:pk>/', views.edit_experience, name='edit_experience'),
    # path('delete-experience/<int:pk>/', views.delete_experience, name='delete_experience'),
    # path('position/', views.add_position, name='add_position'),
    # path('edit-position/<int:pk>/', views.edit_position, name='edit_position'),
    # path('delete-position/<int:pk>/', views.delete_position, name='delete_position'),
    # #Job Post
    # path('add-jobpost/', views.add_jobpost, name='add_jobpost'),
    # path('edit-jobpost/<int:pk>/', views.edit_jobpost, name='edit_jobpost'),
    # path('job-list/', views.job_list, name='job_list'),
    # path('delete-jobpost/<int:pk>/', views.delete_jobpost, name='delete_jobpost'),
    # path('applicant-list/', views.applicant_list, name='applicant_list'),
    # path('delete-applicant/<int:pk>/', views.delete_applicant, name='delete_applicant'),
    # path('applicant-detail/<int:pk>/', views.myapplicant_detail, name='myapplicant_detail'),
    # #Services
    # path('add-services/', views.add_services, name='add_services'),
    # path('services-list/', views.maservices_list, name='maservices_list'),
    # path('edit-services/<int:pk>/', views.edit_services, name='edit_services'),
    # path('delete-services/<int:pk>/', views.delete_services, name='delete_services'),
    # path('add-services-detail/', views.add_services_detail, name='add_services_detail'),
    # path('edit-services-detail/<int:pk>/', views.edit_services_detail, name='edit_services_detail'),
    # path('services-detail-list/', views.maservices_detail_list, name='maservices_detail_list'),
    # path('delete-services-detail/<int:pk>/', views.delete_services_detail, name='delete_services_detail'),
    # #casestudies
    # path('add-casecategory/', views.add_casecategory, name='add_casecategory'),
    # path('casecategory/', views.macasecategory_list, name='macasecategory_list'),
    # path('edit-casecategory/<int:pk>/', views.edit_casecategory, name='edit_casecategory'),
    # path('delete-casecategory/<int:pk>/', views.delete_casecategory, name='delete_casecategory'),
    # path('add-casestudies/', views.add_casestudies, name='add_casestudies'),
    # path('edit-casestudies/<int:pk>/', views.edit_casestudies, name='edit_casestudies'),
    # path('casestudies/', views.macasestudies_list, name='macasestudies_list'),
    # path('delete-casestudies/<int:pk>/', views.delete_casestudies, name='delete_casestudies'),
    # #team
    # path('add-team/', views.add_team, name='add_team'),
    # path('teams/', views.mateam_list, name='mateam_list'),
    # path('edit-team/<int:pk>/', views.edit_team, name='edit_team'),
    # path('delete-teams/<int:pk>/', views.delete_team, name='delete_team'),
    # #client
    # path('add-client/', views.add_client, name='add_client'),
    # path('clients/', views.client_list, name='client_list'),
    # path('edit-client/<int:pk>/', views.edit_client, name='edit_client'),
    # path('delete-client/<int:pk>/', views.delete_client, name='delete_client'),
    # #testimonial
    # path('add-testimonial/', views.add_testimonial, name='add_testimonial'),
    # path('testimonial/', views.testimonial_list, name='testimonial_list'),
    # path('edit-testimonial/<int:pk>/', views.edit_testimonial, name='edit_testimonial'),
    # path('delete-testimonial/<int:pk>/', views.delete_testimonial, name='delete_testimonial'),
    # path('newsletter/<int:pk>/', views.mycontact, name='mycontact'),
    # #json
    # path('get_states/', views.get_states, name='get_states'),
    # path('get_cities/', views.get_cities, name='get_cities'),
    # path('get-job-categories/', views.get_job_categories, name='get_job_categories'),
]